package com.example.freedom.domain.ai

enum class ToolIntent {
    CREATE_MILK_RECORD,
    SEARCH_FARMERS,
    GET_FARMER_HISTORY,
    GET_TODAY_SUMMARY,
    GET_PENDING_PAYMENTS,
    GET_PENDING_UPLOADS,
    GET_WORKER_PROFILE,
    GET_TODAY_WORKER_SUMMARY,
    GET_WEEKLY_WORKER_SUMMARY,
    COUNT_FARMERS_COVERED,
    GET_ORGANIZATION_INFO,
    SEARCH_LOCAL_KNOWLEDGE,
    ASK_CLARIFICATION,
    UNKNOWN_OR_UNSUPPORTED
}
